### ISSUE TITLE
Can not add repository2-1.xml ro sdk manager

### ISSUE THREAD

**Issue by far2005** [renfeng/android-repository#11]
When i add the link i get an error saying "sdk:sdk-repository not found"

**Comment by renfeng** [comment]
What link? Can you help me to reproduce the problem? Thanks.

**Comment by far2005** [comment]
I'm using android studio V3.1.2 
after syncing is done, i try to add "repository2-1.xml" from my server to my sdk manager
i looked around to find it...

**Comment by renfeng** [comment]
Did you follow the instruction on client setup?
https://github.com/renfeng/android-repository#client-setup

**Comment by far2005** [comment]
i did but no luck
android studio tries to connect to google without proxy!
--
and TBH , i don't know how to set SDK_TEST_BASE_URL

**Comment by renfeng** [comment]
The steps are in their simplest, e.g. for macOS, you need to set environment variable to let your Android Studio to use your mirror site. There is no need to add anything manually to your sdk manager.

> how to set SDK_TEST_BASE_URL

Can you google how to open command line for your os?

Then copy and paste something like the following into your command line and hit enter key.
```
export SDK_TEST_BASE_URL=http://studyjams.dushu.hu/android/repository/
open -a 'Android Studio'
```
