### ISSUE TITLE
How to use SDK Manager instead of the old way?

### ISSUE THREAD

**Issue by rogerhu** [renfeng/android-repository#15]
https://github.com/renfeng/android-repository/blob/master/android/studio/template.html

I can do:
```wget https://dl-ssl.google.com/android/repository/sdk-tools-darwin-4333796.zip```

But what is this line do?  The android/studio URL points to the template web page -- how does the nested wget work?

```
wget http://downloads.myhost.com/`wget http://downloads.myhost.com/android/studio/ -O - | perl -nle "print $& if m{android/repository/sdk-tools-darwin-\d+.zip}"
```

Also the extra M2 repositories are not needed anymore given Google's new Maven repo at maven.google.com (or google() in Gradle):

```
tools/bin/sdkmanager --no_https --proxy=http --proxy_host=downloads.codepath.com --proxy_port=80 "patcher;v4" "extras;android;m2repository" "extras;google;m2repository" emulator "build-tools;25.0.3" "platforms;android-25" platform-tools tools "sources;android-25"
```

I also don't think the patcher stuff either for API 27?

**Comment by renfeng** [comment]
It looks like several questions...

> How to use SDK Manager instead of the old way?

If it was the old standalone sdk manager with a gui, it doesn't seem available any more. So, the answer would be impossible.

> But what is this line do?

```
wget http://downloads.myhost.com/`wget http://downloads.myhost.com/android/studio/ -O - | perl -nle "print $& if m{android/repository/sdk-tools-darwin-\d+.zip}"
```
It downloads sdk-tools-darwin-4333796.zip from your mirror web site. An equivalent to
```
wget http://downloads.myhost.com/android/repository/sdk-tools-darwin-4333796.zip
``` 

> how does the nested wget work?

https://unix.stackexchange.com/questions/48392/understanding-backtick

> the extra M2 repositories (m2repository) are not needed anymore

This was an outdated example. I guess It was written for API 25
- build-tools;25.0.3
- platforms;android-25
- sources;android-25
