### ISSUE TITLE
something about jcenter.bintray.com

### ISSUE THREAD

**Issue by far2005** [renfeng/android-repository#17]
Hey
Thanks for SDK sample.
Can you do something for jcenter.bintray.com repo?

I mean a mirror repo

**Comment by renfeng** [comment]
Can you leave more details here, or email it to me? Thanks.

**Comment by far2005** [comment]
Well we know that many libraries are hosted on  jcenter.bintray.com and when we start a new project android studio connects to  jcenter.bintray.com to update its packages.
maybe we could create a local repository?

**Comment by renfeng** [comment]
If android studio can retrieve files from one server, surely it can do so from another. Since the directory structure can be browsed, wget should work for you. See https://www.gnu.org/software/wget/manual/html_node/Recursive-Retrieval-Options.html

**Comment by far2005** [comment]
my point is
how can we tweak android studio to fetch our repo instead of jcenter.bintray.com ?

**Comment by renfeng** [comment]
By default, android studio doesn't fetch files from jcenter.bintray.com, does it? So, there must have been tweaks to your android studio, which is not supported here. You can ask the people who did it.

**Comment by far2005** [comment]
well android studio 3.1.2 users jcenter by default
i have just installed it to be sure!

**Comment by renfeng** [comment]
Can you show me a screenshot?

I didn't see anything like jcenter. This is from my installation.

Android Studio 3.1.2
Build #AI-173.4720617, built on April 14, 2018
JRE: 1.8.0_152-release-1024-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

![image](https://user-images.githubusercontent.com/449029/41110412-db8f4586-6aab-11e8-93a8-680a4d59e4e9.png)

**Comment by far2005** [comment]
oh
Jcenter is not in SDK libraries
Jcenter is for gradle, when you add a new package to project or the fresh installation of AStudio

**Comment by renfeng** [comment]
Can you list the files fetched from jcenter? It would be helpful if you can list the urls for downloading those files. Thanks.

**Comment by renfeng** [comment]
This feature shall not be a goal of this project. The project name, android-repository, was derived from the URL of the files it downloads.
