### ISSUE TITLE
About Android Gradle plugin and Google Maven

### ISSUE THREAD

**Issue by darvinrivera** [renfeng/android-repository#19]
Can you add offline Android Gradle plugin and Google Maven available in official site?
This is the Offline components:
https://dl.google.com/android/studio/plugins/android-gradle/preview/offline-android-gradle-plugin-preview.zip
https://dl.google.com/android/studio/maven-google-com/stable/offline-gmaven-stable.zip
Thanks.

**Comment by renfeng** [comment]
Thanks for the request. Since the repository is getting more and more standard, the download script is shrinking. Unless someone else would be interested in contributing in that direction, I'm closing this.
