### ISSUE TITLE
it seems that some items cannot download

### ISSUE THREAD

**Issue by wilsonssss** [renfeng/android-repository#6]
![image](https://cloud.githubusercontent.com/assets/4098951/9511612/f215f6fa-4caa-11e5-92b1-c5a3189c9832.png)

for example, support library  just downloaded 2 package, and build-tools  cannot download older versions such as build-tools_r16,17,18, etc.

how can i download full packages?

**Comment by wilsonssss** [comment]
And then it just downloaded 14G packages, tell  me why?

**Comment by wilsonssss** [comment]
android/repository/addon.xml:1224:                sdk:urlhttp://studyjams.dushu.hu/googleadmobadssdk/googleadmobadssdkandroid-6.4.1.zip/sdk:url
android/repository/addon.xml:1246:                sdk:urlhttp://studyjams.dushu.hu/gaformobileapps/GoogleAnalyticsAndroid_2.0beta5.zip/sdk:url
android/repository/repository-10.xml:299:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.1_r1-windows.zip/sdk:url
android/repository/repository-10.xml:305:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.1_r1-macosx.zip/sdk:url
android/repository/repository-10.xml:311:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.1_r1-linux.zip/sdk:url
android/repository/repository-10.xml:337:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.5_r04-windows.zip/sdk:url
android/repository/repository-10.xml:343:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.5_r04-macosx.zip/sdk:url
android/repository/repository-10.xml:349:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.5_r04-linux.zip/sdk:url
android/repository/repository-10.xml:374:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.6_r03-linux.zip/sdk:url
android/repository/repository-10.xml:380:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.6_r03-macosx.zip/sdk:url
android/repository/repository-10.xml:386:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-1.6_r03-windows.zip/sdk:url
android/repository/repository-10.xml:413:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.0_r01-linux.zip/sdk:url
android/repository/repository-10.xml:419:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.0_r01-macosx.zip/sdk:url
android/repository/repository-10.xml:425:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.0_r01-windows.zip/sdk:url
android/repository/repository-10.xml:452:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.0.1_r01-linux.zip/sdk:url
android/repository/repository-10.xml:458:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.0.1_r01-macosx.zip/sdk:url
android/repository/repository-10.xml:464:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.0.1_r01-windows.zip/sdk:url
android/repository/repository-10.xml:491:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.1_r03-linux.zip/sdk:url
android/repository/repository-10.xml:516:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.2_r03-linux.zip/sdk:url
android/repository/repository-10.xml:542:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.3.1_r02-linux.zip/sdk:url
android/repository/repository-10.xml:567:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-2.3.3_r02-linux.zip/sdk:url
android/repository/repository-10.xml:593:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-3.0_r02-linux.zip/sdk:url
android/repository/repository-10.xml:621:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-3.1_r03-linux.zip/sdk:url
android/repository/repository-10.xml:647:                sdk:urlhttp://studyjams.dushu.hu/android/repository/android-3.2_r01-linux.zip/sdk:url
android/repository/repository-10.xml:898:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-2.1_r01-linux.zip/sdk:url
android/repository/repository-10.xml:916:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-2.2_r01-linux.zip/sdk:url
android/repository/repository-10.xml:935:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-2.3_r01-linux.zip/sdk:url
android/repository/repository-10.xml:953:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-2.3.3_r01-linux.zip/sdk:url
android/repository/repository-10.xml:972:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-3.0_r01-linux.zip/sdk:url
android/repository/repository-10.xml:991:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-3.1_r01-linux.zip/sdk:url
android/repository/repository-10.xml:1010:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-3.2_r01-linux.zip/sdk:url
android/repository/repository-10.xml:1025:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-14_r02.zip/sdk:url
android/repository/repository-10.xml:1039:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-15_r02.zip/sdk:url
android/repository/repository-10.xml:1053:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-16_r01.zip/sdk:url
android/repository/repository-10.xml:1067:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-17_r01.zip/sdk:url
android/repository/repository-10.xml:1081:                sdk:urlhttp://studyjams.dushu.hu/android/repository/samples-18_r01.zip/sdk:url
android/repository/repository-10.xml:1203:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r17-windows.zip/sdk:url
android/repository/repository-10.xml:1209:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r17-linux.zip/sdk:url
android/repository/repository-10.xml:1215:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r17-macosx.zip/sdk:url
android/repository/repository-10.xml:1236:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.0.1-windows.zip/sdk:url
android/repository/repository-10.xml:1242:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.0.1-linux.zip/sdk:url
android/repository/repository-10.xml:1248:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.0.1-macosx.zip/sdk:url
android/repository/repository-10.xml:1267:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.1-windows.zip/sdk:url
android/repository/repository-10.xml:1273:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.1-linux.zip/sdk:url
android/repository/repository-10.xml:1279:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.1-macosx.zip/sdk:url
android/repository/repository-10.xml:1298:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.1.1-windows.zip/sdk:url
android/repository/repository-10.xml:1304:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.1.1-linux.zip/sdk:url
android/repository/repository-10.xml:1310:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r18.1.1-macosx.zip/sdk:url
android/repository/repository-10.xml:1329:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19-windows.zip/sdk:url
android/repository/repository-10.xml:1335:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19-linux.zip/sdk:url
android/repository/repository-10.xml:1341:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19-macosx.zip/sdk:url
android/repository/repository-10.xml:1360:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.1-windows.zip/sdk:url
android/repository/repository-10.xml:1366:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.1-linux.zip/sdk:url
android/repository/repository-10.xml:1372:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.1-macosx.zip/sdk:url
android/repository/repository-10.xml:1391:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.2-windows.zip/sdk:url
android/repository/repository-10.xml:1397:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.2-linux.zip/sdk:url
android/repository/repository-10.xml:1403:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.2-macosx.zip/sdk:url
android/repository/repository-10.xml:1422:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.3-windows.zip/sdk:url
android/repository/repository-10.xml:1428:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.3-linux.zip/sdk:url
android/repository/repository-10.xml:1434:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.0.3-macosx.zip/sdk:url
android/repository/repository-10.xml:1452:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.1-windows.zip/sdk:url
android/repository/repository-10.xml:1458:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.1-linux.zip/sdk:url
android/repository/repository-10.xml:1464:                sdk:urlhttp://studyjams.dushu.hu/android/repository/build-tools_r19.1-macosx.zip/sdk:url
android/repository/repository-10.xml:1853:                sdk:urlhttp://studyjams.dushu.hu/android/repository/sources-14_r01.zip/sdk:url
android/repository/repository-10.xml:1867:                sdk:urlhttp://studyjams.dushu.hu/android/repository/sources-15_r02.zip/sdk:url
android/repository/repository-10.xml:1881:                sdk:urlhttp://studyjams.dushu.hu/android/repository/sources-16_r02.zip/sdk:url
android/repository/repository-10.xml:1895:                sdk:urlhttp://studyjams.dushu.hu/android/repository/sources-17_r01.zip/sdk:url
android/repository/repository-10.xml:1909:                sdk:urlhttp://studyjams.dushu.hu/android/repository/sources-18_r01.zip/sdk:url
android/repository/repository-10.xml:1923:                sdk:urlhttp://studyjams.dushu.hu/android/repository/sources-19_r02.zip/sdk:url
android/repository/addons_list-2.xml:31:      sdk:urlhttp://studyjams.dushu.hu/glass/gdk/addon.xml/sdk:url
glass/gdk/addon.xml:180:                sdk:urlhttp://studyjams.dushu.hu/glass/xe22/google-gdk.zip/sdk:url

### I Got this after run download.sh,  we dont need files from studyjams.dushu.hu, would  u tell why change to this host.

**Comment by ali-zohrevand** [comment]
i have this problem too!!!!! could help us ...
![screen shot - - at](https://cloud.githubusercontent.com/assets/4710446/9628738/a2cb8204-5182-11e5-94e3-67a75dc5c20f.png)

**Comment by renfeng** [comment]
Hi, wilsonssss and c0otlass,

I'll look into this, and get back soon. Sorry, I missed the github message about your issue in my gmail, renfeng.cn@gmail.com

Please hold on :)

Frank

**Comment by renfeng** [comment]
You can safely ignore studyjams.dushu.hu, which is a legacy when the mirror was accessed by manipulating your etc/hosts file.

For the up to date usage, please read this page of the slides, [Setup your client (SDK Manager)](https://docs.google.com/presentation/d/1JnGpK3YJrMY-f3M0pq6RkyAu2p-wct6DCwCOacCDGO8/edit#slide=id.g9a20617bb_0_8).

Let me know if that works.

**Comment by renfeng** [comment]
Back to the verify first question of the issue, it's intended not to download obsolete sdk packages.

[Obsolete packages ignore](https://docs.google.com/presentation/d/1JnGpK3YJrMY-f3M0pq6RkyAu2p-wct6DCwCOacCDGO8/edit#slide=id.gbb3c64539_0_6)
- Build-tools 17 and 18 are obsolete
- 16 is not even on the list any more

If it's desirable to have obsolete sdk package mirrored, you can modify xsl files, e.g.

change

<xsl:for-each select="sdk:*[not(sdk:obsolete)]/sdk:archives/sdk:archive/sdk:url">

to

<xsl:for-each select="sdk:*/sdk:archives/sdk:archive/sdk:url">

**Comment by renfeng** [comment]
I'm closing this. Please open another issue if you should have any problem with the proxy settings for SDK manager. Thanks.
