### ISSUE TITLE
studyjams.dushu.hu files cand download

### ISSUE THREAD

**Issue by ali-zohrevand** [renfeng/android-repository#7]
Hi ...
in the issue https://github.com/renfeng/android-repository/issues/6 i asked about my problem ...
![a2cb8204-5182-11e5-94e3-67a75dc5c20f](https://cloud.githubusercontent.com/assets/4710446/9975194/ef81ac34-5ec7-11e5-90d8-d5b500c605eb.png)
you kindly answered i must edit etc/hosts ...
could tell me exactly how and what must be edited text
thank you

**Comment by renfeng** [comment]
Hi Ali,

You don't have to edit etc/hosts file any more. Please refer to the [latest guide](https://docs.google.com/presentation/d/1JnGpK3YJrMY-f3M0pq6RkyAu2p-wct6DCwCOacCDGO8/edit#slide=id.g9a20617bb_0_8).
